Expand the Plentiful Item Pool
Z3DR/MM3D_Randomizer pull request #90
Opened 2024-04-09 01:24 UTC by CharadeNut

• Adds duplicates for all major items and one tier of every upgrade; • Adds duplicates for all masks;
• Replaces 48 Pieces of Heart with 12 Heart Containers.

The app menu is adjusted to lock Shuffle Piece of Heart while the Plentiful pool is active.

2024-04-09 12:49 UTC, PhlexPlexico commented on Z3DR
I'm not sure if this is actually in the subrepo. Please create a PR in mm3dr that includes those option, then update the subrepo in your project.

2024-04-09 13:47 UTC, PhlexPlexico requested changes
Aside from submitting the PR to the mm3dr with the updated `settings.h`, this looks good to me.

2024-04-10 03:38 UTC, CharadeNut commented on Z3DR
This change was rescinded after Tacoman's feedback, Z3DR no longer has any change by this PR.

2024-04-16 15:16 UTC, PhlexPlexico approved these changes

2024-04-16 15:17 UTC, merged